name: Artifactory

on:
  workflow_dispatch: # manual trigger
  #release:
  #  types: [published]

jobs:
  publish:
    # if: startsWith(github.event.ref, 'release/')
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          use-policy-store: true
          api-key: ${{ secrets.STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # so gradle doesn't fail traversing the history
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: microsoft
          cache: gradle
      - uses: gradle/actions/setup-gradle@v4 # v4.0.0
      - name: publish
        run: |
          ./gradlew :artifactoryPublish :cruise-control:artifactoryPublish :cruise-control-core:artifactoryPublish :cruise-control-metrics-reporter:artifactoryPublish
